const canvas=document.getElementById('particles');const ctx=canvas.getContext('2d');let particles=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);for(let i=0;i<130;i++)particles.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.8+.3,v:Math.random()*.35+.08,a:Math.random()*Math.PI*2});function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);for(const p of particles){p.y-=p.v;p.x+=Math.sin(p.a+=.005)*.12;if(p.y<0)p.y=canvas.height;ctx.globalAlpha=.15+Math.random()*.45;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}requestAnimationFrame(animate)}animate();

// Cinematic opening sequence + typewriter introduction
const opening=document.getElementById('opening');const enterBtn=document.getElementById('enterBtn');const openingLine=document.getElementById('openingLine');const lines=['And this isn’t an ordinary birthday wish.','For a few moments, the world can slow down.','Because today deserves a little extra magic.','Ready? Let the celebration begin. ✨'];let lineIndex=0;function typeLine(text){openingLine.textContent='';let i=0;const timer=setInterval(()=>{openingLine.textContent+=text[i++]||'';if(i>text.length)clearInterval(timer)},38)}setTimeout(()=>typeLine(lines[0]),900);let introTimer=setInterval(()=>{lineIndex++;if(lineIndex<lines.length)typeLine(lines[lineIndex]);else clearInterval(introTimer)},2600);

// Gentle musical birthday atmosphere using Web Audio — starts only after a user gesture
let audioCtx=null,master=null,musicOn=false,melodyTimer=null;const notes=[261.63,293.66,329.63,392,329.63,293.66,261.63,392,440,392,329.63,293.66];function playNote(freq,time,duration=.65){if(!audioCtx||!master)return;const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0.0001,time);gain.gain.exponentialRampToValueAtTime(.045,time+.05);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain);gain.connect(master);osc.start(time);osc.stop(time+duration+.03)}function startMusic(){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();master=audioCtx.createGain();master.gain.value=.65;master.connect(audioCtx.destination);musicOn=true;let n=0;const schedule=()=>{if(!musicOn)return;const now=audioCtx.currentTime;for(let i=0;i<notes.length;i++)playNote(notes[i],now+i*.48,.62);melodyTimer=setTimeout(schedule,notes.length*.48*1000-120)};schedule();document.getElementById('musicControl').classList.remove('off')}function stopMusic(){musicOn=false;if(melodyTimer)clearTimeout(melodyTimer);if(master)master.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.25);document.getElementById('musicControl').classList.add('off')}

const confetti=document.getElementById('confetti');const toast=document.getElementById('toast');const wishBtn=document.getElementById('wishBtn');const wishResult=document.getElementById('wishResult');const messages=['Your wish is on its way to the stars ✨','The universe is listening. Keep believing. 🌙','A beautiful year is waiting for you. 💫','May this wish become your favorite memory. ♡'];function burst(count=110){for(let i=0;i<count;i++){const el=document.createElement('i');el.className='confetti';el.style.left=Math.random()*100+'%';el.style.animationDelay=Math.random()*.7+'s';el.style.transform=`rotate(${Math.random()*360}deg)`;el.style.background=['#ff72b6','#fff','#a58bff','#65dcff','#ffd166'][Math.floor(Math.random()*5)];el.style.borderRadius=Math.random()>.5?'50%':'2px';confetti.appendChild(el);setTimeout(()=>el.remove(),3800)}}function showToast(){toast.textContent='✨ '+messages[Math.floor(Math.random()*messages.length)];toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500)}

function enterExperience(){document.body.classList.remove('locked');opening.classList.add('hide');startMusic();burst(70);setTimeout(()=>document.getElementById('hero').scrollIntoView({behavior:'smooth'}),500)}enterBtn.onclick=enterExperience;document.getElementById('musicControl').onclick=()=>{if(musicOn)stopMusic();else startMusic()};document.getElementById('celebrateBtn').onclick=()=>{document.getElementById('cakeSection').scrollIntoView({behavior:'smooth'});setTimeout(()=>burst(140),650)};document.getElementById('skipBtn').onclick=()=>document.querySelector('.story').scrollIntoView({behavior:'smooth'});wishBtn.onclick=()=>{wishBtn.disabled=true;wishBtn.textContent='Wish Made ✨';wishResult.textContent='Your wish is now a secret between you and the universe...';burst(150);showToast();setTimeout(()=>wishBtn.disabled=false,3000)};document.getElementById('againBtn').onclick=()=>{scrollTo({top:0,behavior:'smooth'});setTimeout(burst,900)};

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

// Premium pointer glow on desktop cards
if(matchMedia('(pointer:fine)').matches){document.querySelectorAll('.wish-card,.glass').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.background=`radial-gradient(circle at ${e.clientX-r.left}px ${e.clientY-r.top}px, rgba(255,120,200,.10), transparent 35%), linear-gradient(145deg,rgba(255,255,255,.095),rgba(255,255,255,.025))`}))}