const canvas=document.getElementById('particles');const ctx=canvas.getContext('2d');let particles=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);for(let i=0;i<150;i++)particles.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.8+.3,v:Math.random()*.35+.08,a:Math.random()*6.28});function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);for(const p of particles){p.y-=p.v;p.x+=Math.sin(p.a+=.005)*.12;if(p.y<0)p.y=canvas.height;ctx.globalAlpha=.12+Math.random()*.4;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}requestAnimationFrame(animate)}animate();

// Opening typewriter
const opening=document.getElementById('opening'),enterBtn=document.getElementById('enterBtn'),openingLine=document.getElementById('openingLine');const introLines=['This is not just a birthday page.','It is five little moments made especially for today.','There will be wishes, a song, a candle, and a surprise.','Ready? Let the celebration begin. ✨'];let li=0;function typeLine(text){openingLine.textContent='';let i=0;const t=setInterval(()=>{openingLine.textContent+=text[i++]||'';if(i>text.length)clearInterval(t)},35)}setTimeout(()=>typeLine(introLines[0]),700);const introTimer=setInterval(()=>{li++;if(li<introLines.length)typeLine(introLines[li]);else clearInterval(introTimer)},2300);

// Web Audio birthday-song melody. Starts only after the visitor taps, so browser autoplay is respected.
let audioCtx=null,master=null,musicOn=false,songTimer=null;const beat=.38;const song=[
  [261.63,1],[261.63,1],[293.66,2],[261.63,2],[349.23,2],[329.63,4],
  [261.63,1],[261.63,1],[293.66,2],[261.63,2],[392.00,2],[349.23,4],
  [261.63,1],[261.63,1],[523.25,2],[440.00,2],[349.23,2],[329.63,2],[293.66,4],
  [466.16,1],[466.16,1],[440.00,2],[349.23,2],[392.00,2],[349.23,4]
];
function playNote(freq,time,duration){if(!audioCtx||!master)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,time);gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(.055,time+.035);gain.gain.exponentialRampToValueAtTime(.0001,time+duration-.04);osc.connect(gain);gain.connect(master);osc.start(time);osc.stop(time+duration)}
function startMusic(){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();if(master)master.disconnect();master=audioCtx.createGain();master.gain.value=.72;master.connect(audioCtx.destination);musicOn=true;const schedule=()=>{if(!musicOn)return;const now=audioCtx.currentTime+.05;let offset=0;for(const [freq,beats] of song){const duration=beats*beat;playNote(freq,now+offset,duration*.94);offset+=duration}songTimer=setTimeout(schedule,offset*1000-120)};schedule();document.getElementById('musicControl').classList.remove('off');document.getElementById('musicControl').textContent='♫'}
function stopMusic(){musicOn=false;if(songTimer)clearTimeout(songTimer);if(master&&audioCtx)master.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.25);document.getElementById('musicControl').classList.add('off');document.getElementById('musicControl').textContent='🔇'}

// Five-screen navigation
const pages=[...document.querySelectorAll('.page')],dots=[...document.querySelectorAll('#dots button')],count=document.getElementById('chapterCount');let current=1;function showPage(n,dir=1){n=Math.max(1,Math.min(5,n));if(n===current&&pages[n-1].classList.contains('active'))return;pages[current-1].classList.remove('active');current=n;pages[current-1].classList.add('active');count.textContent=String(current).padStart(2,'0')+' / 05';dots.forEach((d,i)=>d.classList.toggle('active',i===current-1));if(dir>0)burst(current===5?180:70);}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showPage(Number(b.dataset.next),1)));dots.forEach((d,i)=>d.addEventListener('click',()=>showPage(i+1,i+1>current?1:-1)));
let wheelLock=false;addEventListener('wheel',e=>{if(document.body.classList.contains('locked')||wheelLock)return;wheelLock=true;if(Math.abs(e.deltaY)>20)showPage(current+(e.deltaY>0?1:-1),e.deltaY>0?1:-1);setTimeout(()=>wheelLock=false,900)},{passive:true});addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown')showPage(current+1,1);if(e.key==='ArrowLeft'||e.key==='ArrowUp')showPage(current-1,-1)});
let touchY=0;addEventListener('touchstart',e=>touchY=e.touches[0].clientY,{passive:true});addEventListener('touchend',e=>{const dy=touchY-e.changedTouches[0].clientY;if(Math.abs(dy)>55)showPage(current+(dy>0?1:-1),dy>0?1:-1)},{passive:true});

// Confetti and surprise messages
const confetti=document.getElementById('confetti'),toast=document.getElementById('toast');function burst(count=100){for(let i=0;i<count;i++){const el=document.createElement('i');el.className='confetti';el.style.left=Math.random()*100+'%';el.style.animationDelay=Math.random()*.65+'s';el.style.background=['#ff72b6','#fff','#a58bff','#65dcff','#ffd166'][Math.floor(Math.random()*5)];el.style.borderRadius=Math.random()>.5?'50%':'2px';confetti.appendChild(el);setTimeout(()=>el.remove(),3500)}}function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3400)}
function enterExperience(){document.body.classList.remove('locked');opening.classList.add('hide');startMusic();burst(110);showPage(1)}enterBtn.onclick=enterExperience;document.getElementById('musicControl').onclick=()=>musicOn?stopMusic():startMusic();

// Wish interaction: candle reacts, screen celebrates, and final chapter unlocks.
const wishBtn=document.getElementById('wishBtn'),wishResult=document.getElementById('wishResult'),afterWish=document.getElementById('afterWish');wishBtn.onclick=()=>{wishBtn.disabled=true;wishBtn.textContent='Wish Received ✨';wishResult.textContent='Your wish is safe now — between your heart and the universe.';document.querySelector('.cake-stage').classList.add('wish-made');burst(180);showToast('✨ Your wish has been sent into the stars.');setTimeout(()=>afterWish.classList.remove('hidden'),900)};

document.getElementById('againBtn').onclick=()=>{showPage(1,-1);burst(140);showToast('✨ The magic begins again.');};

// Desktop pointer light
if(matchMedia('(pointer:fine)').matches){document.querySelectorAll('.glass,.wish').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.background=`radial-gradient(circle at ${e.clientX-r.left}px ${e.clientY-r.top}px,rgba(255,120,200,.11),transparent 32%),linear-gradient(145deg,rgba(255,255,255,.095),rgba(255,255,255,.025))`}))}
